# This file is used to manage ipfs nodes
version: "2.1"
services:
    ipfs_0:
        container_name: dev_ipfs_0
        image: ipfs/go-ipfs:latest
        environment:
            IPFS_SWARM_KEY: |-
                /key/swarm/psk/1.0.0/
                /base16/
                9cb41930f9cfaf5f1217f9a2f8c6ee7c459cb619e1b4a4553e1616b15ffe0f90
            LIBP2P_FORCE_PNET: "1"
        volumes:
            - ipfs_staging_0:/export
            - ipfs_data_0:/data/ipfs
        ports:
            - 10206:5001
            - 10207:8080
        healthcheck:
            test:
                - CMD-SHELL
                - wget --post-data= http://127.0.0.1:5001/api/v0/id -O - -q
            interval: 5s
            timeout: 3s
            retries: 12
        logging:
            driver: json-file
            options:
                max-file: "1"
                max-size: 10m
    ipfs_1:
        container_name: dev_ipfs_1
        image: ipfs/go-ipfs:latest
        environment:
            IPFS_SWARM_KEY: |-
                /key/swarm/psk/1.0.0/
                /base16/
                9cb41930f9cfaf5f1217f9a2f8c6ee7c459cb619e1b4a4553e1616b15ffe0f90
            LIBP2P_FORCE_PNET: "1"
        volumes:
            - ipfs_staging_1:/export
            - ipfs_data_1:/data/ipfs
        ports:
            - 10406:5001
            - 10407:8080
        healthcheck:
            test:
                - CMD-SHELL
                - wget --post-data= http://127.0.0.1:5001/api/v0/id -O - -q
            interval: 5s
            timeout: 3s
            retries: 12
        logging:
            driver: json-file
            options:
                max-file: "1"
                max-size: 10m
    ipfs_2:
        container_name: dev_ipfs_2
        image: ipfs/go-ipfs:latest
        environment:
            IPFS_SWARM_KEY: |-
                /key/swarm/psk/1.0.0/
                /base16/
                9cb41930f9cfaf5f1217f9a2f8c6ee7c459cb619e1b4a4553e1616b15ffe0f90
            LIBP2P_FORCE_PNET: "1"
        volumes:
            - ipfs_staging_2:/export
            - ipfs_data_2:/data/ipfs
        ports:
            - 10606:5001
            - 10607:8080
        healthcheck:
            test:
                - CMD-SHELL
                - wget --post-data= http://127.0.0.1:5001/api/v0/id -O - -q
            interval: 5s
            timeout: 3s
            retries: 12
        logging:
            driver: json-file
            options:
                max-file: "1"
                max-size: 10m

volumes:
    ipfs_data_0: {}
    ipfs_data_1: {}
    ipfs_data_2: {}
    ipfs_staging_0: {}
    ipfs_staging_1: {}
    ipfs_staging_2: {}
